<a href="https://colab.research.google.com/github/naga-sk/DataScienceTraining/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version

In [ ]:
np.__version__

'1.21.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
nvec = np.zeros(10)
print(nvec)
print(nvec.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64


In [ ]:
arr = np.array(10)
arr.itemsize
arr.ndim

0

In [ ]:
arr1 = np.array([1,2,3])
arr1.size
arr1.ndim

1

In [ ]:
#Problem 4: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
nvec = np.zeros(10)
nvec[4] = 1
print(nvec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
float64


#### 4. Numpy where Problem

Say we have a numpy array A 

[[1 2 3]
 [4 5 6]]

Create a new matrix with Indices of elements <4

Output
Elements which are <4
array([1, 2, 3])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[arr < 4])


[1 2 3]


#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = np.arange(10,20)
print(arr)

# Method 1 to print in reverse order using range reversal
rev1 = arr[::-1] 
print(rev1)

# Method 2 to first reverse the order using a function and then print
rev2 = np.flip(arr)
print(rev2)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]
[19 18 17 16 15 14 13 12 11 10]


#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr = np.arange(0,9)
print(arr)

three = arr.reshape(3,3)
print(three)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
from numpy.core.numeric import indices
arr = np.array([1,2,0,0,4,0])
zerInd = np.nonzero(arr)
print (zerInd)

#This prints the elements that are not zero
a = arr[arr != 0]
print(a)

(array([0, 1, 4]),)
[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [2]:
import numpy as np
arr = np.identity(3, dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
import numpy as np
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [6]:
y = np.random.random(size=(3,3,3))
print(y)

[[[0.28273073 0.77022699 0.31004234]
  [0.63399767 0.63494803 0.26766493]
  [0.97742993 0.41343739 0.29823495]]

 [[0.47115633 0.97897842 0.57721438]
  [0.49938309 0.87004248 0.78001514]
  [0.61497085 0.38426357 0.21167658]]

 [[0.93710742 0.26813669 0.71703958]
  [0.21376323 0.55343359 0.33807667]
  [0.93278225 0.07123021 0.72150396]]]


In [7]:
x = np.random.randint(10, size=(3,3,3))
print(x)

[[[9 2 0]
  [9 1 6]
  [3 6 9]]

 [[6 8 0]
  [0 7 0]
  [7 5 7]]

 [[0 1 3]
  [1 5 9]
  [0 1 4]]]


In [8]:
a=np.random.randint(1,50,(3,3,3))
print(a)

[[[44 31  2]
  [12 22 12]
  [21 43 33]]

 [[27 28 24]
  [ 4 16 11]
  [47 12 13]]

 [[ 7  2 41]
  [45 18 36]
  [23  1 46]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x = np.random.randint(1000, size=(10,10))
print(x)

print(np.amax(x))
print(np.amin(x))

[[ 66  99 495 409 455 213 394 997  17 382]
 [129 183 763 114 350 900 697 506 224 372]
 [335 492 983 664 261 794  55 912 331 137]
 [434 704 112 433 901 252 301 796 962 335]
 [607 650  53 181 581 265 846  79 292 673]
 [829 580  53 126 658 337  71 727 641 969]
 [383 661 671 643 913 911 291 533 323 209]
 [831 845 515 881  32 431 903  51 633 258]
 [248 445 637 832 468 669 445 585 395 316]
 [651 680 136 434 488 880 837 133 864 638]]
997
17


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
x = np.random.randint(30, size=30)
print(x)

print(np.mean(x))

[20 24 11  7 28  3 12 20  3  7 27 12 13 13 21 27 17  8 23  1 20 20  1 10
  1 25 14 22 27 14]
15.033333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
import numpy as np
x = np.ones((4,4))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
import numpy as np
x = np.ones((4,4))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan

nan

In [18]:
np.nan == np.nan

False

In [19]:
np.inf > np.nan

False

In [20]:
np.nan - np.nan

nan

In [21]:
np.nan in set([np.nan])

True

In [22]:
0.3 == 3 * 0.1

False

#### 18. Create a 4x4 matrix with values 0,1,2,3 just below the diagonal (★☆☆)

In [24]:
import numpy as np
arr = np.diag([1, 2, 3, 4, 5],-1)
print(arr)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)



In [25]:
nvec = np.zeros(10, dtype=int)
print(nvec)

nvec[4] = 5
print(nvec)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 5 0 0 0 0 0]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
Say X is 5*5 numpy array  Normalize i.e X - mean(X) / Standard Deviation of X

In [28]:
import numpy as np
x= np.random.randint(100, size=(5,5))
print(x)

xmean, xsd = np.mean(x), np.std(x)
x = (x - xmean)/xsd
print(x)

[[91 61 67 86 65]
 [ 7 14 16 88 16]
 [59 23 26 18 81]
 [90 20 76 80 70]
 [80  6 87 25 49]]
[[ 1.28205181  0.29484559  0.49228684  1.11751744  0.42647309]
 [-1.48212561 -1.25177749 -1.18596374  1.18333119 -1.18596374]
 [ 0.22903184 -0.95561562 -0.856895   -1.12014999  0.95298307]
 [ 1.24914494 -1.05433624  0.7884487   0.9200762   0.59100746]
 [ 0.9200762  -1.51503248  1.15042432 -0.88980187 -0.1000369 ]]


#### 24. Do a dot product of 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [33]:
a = np.random.randint(15, size=(5,3))
print(a)

[[ 8  7 12]
 [ 1  9  9]
 [ 6  4  3]
 [ 6  7 10]
 [ 5  4 10]]


In [34]:
b = np.random.randint(15, size=(3,2))
print(b)

[[ 6 14]
 [ 9  2]
 [13  4]]


In [35]:
print(np.dot(a, b))
# print(np.dot(b, a)) - This is not possible since the dimensions don't align

[[267 174]
 [204  68]
 [111 104]
 [229 138]
 [196 118]]


#### 25. Consider two random array A and B, check if they are equal (★★☆)

In [37]:
a = np.random.randint(10, size=(3,3))
print(a)
b = np.random.randint(10, size=(3,3))
print(b)
np.equal(a,b)

[[8 5 6]
 [4 5 3]
 [8 8 6]]
[[0 5 9]
 [4 9 2]
 [9 0 8]]


array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

#### 26. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [44]:
a = np.random.randint(10, size=10)
print(a)
a[np.argmax(a)] = 0
print(a)

[1 3 7 6 3 7 7 6 1 0]
[1 3 0 6 3 7 7 6 1 0]


#### 27. Subtract the mean of each row of a matrix (★★☆):

In [49]:
a = np.random.randint(10, size=(3,3))
print(a)

mean = np.mean(a, axis=1)
print(mean)

a = a-mean
print (a)

[[7 9 2]
 [7 5 1]
 [8 8 5]]
[6.         4.33333333 7.        ]
[[ 1.          4.66666667 -5.        ]
 [ 1.          0.66666667 -6.        ]
 [ 2.          3.66666667 -2.        ]]
